version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wordle-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5rj0nm6mu8ch"
s3_prefix = "wordle-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
