AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WordleBot

  Sample SAM Template for WordleBot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active

Resources:
  WordleBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: WordleBot
      CodeUri: WordleBot/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AmazonSSMReadOnlyAccess
      Events:
        WordleBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wordlebot
            Method: post

  WordleBotSyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: WordleBotSync
      CodeUri: WordleBotSync/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AmazonSSMReadOnlyAccess
    
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WordleBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Wordle Bot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wordlebot/"
  WordleBotFunction:
    Description: "Wordle Bot Lambda Function ARN"
    Value: !GetAtt WordleBotFunction.Arn
  WordleBotFunctionIamRole:
    Description: "Implicit IAM Role created for Wordle Bot function"
    Value: !GetAtt WordleBotFunctionRole.Arn
